// resources/js/Pages/Welcome.jsx
import React from "react";
import { Link, Head } from "@inertiajs/inertia-react";
import BaseLayout from "@/Layouts/BaseLayout";
import BlogsRow from "@/Components/BlogsRow";

export default function Welcome({ blogs }) {
    return (
        <>
            <Head title="Welcome" />
            <BaseLayout>
                <BlogsRow className="pb-10 mt-4" blogs={blogs} />
            </BaseLayout>
        </>
    );
}

// resources/js/Pages/Welcome.vue
<script setup>
import { Head, Link } from "@inertiajs/inertia-vue3";
import BaseLayout from "@/Layouts/BaseLayout.vue";
import BlogsRow from "../Components/BlogsRow.vue";

defineProps({
  blogs: Object,
});
</script>

<template>
  <Head title="Welcome" />

  <BaseLayout>
    <BlogsRow class="pb-10 mt-4" :blogs="blogs" />
  </BaseLayout>
</template>
