// resources/js/Components/Blogs/CreateEditBlog.vue
<script setup>
import { useForm } from "@inertiajs/inertia-vue3";
import InputError from "@/Components/InputError.vue";
import PrimaryButton from "@/Components/PrimaryButton.vue";
import { QuillEditor } from "@vueup/vue-quill";
import ImageUploader from "quill-image-uploader";
import "@vueup/vue-quill/dist/vue-quill.snow.css";
import axios from "axios";
import { QuillDeltaToHtmlConverter } from "quill-delta-to-html";
import { ref } from "vue";

const props = defineProps(["blog"]);

const modules = {
  name: "imageUploader",
  module: ImageUploader,
  options: {
    upload: (file) => {
      return new Promise((resolve, reject) => {
        const formData = new FormData();
        formData.append("image", file);

        axios
          .post("/upload-image", formData)
          .then((res) => {
            resolve(res.data.url);
          })
          .catch((err) => {
            reject("Upload failed");
          });
      });
    },
  },
};

const toolbar = [
  [{ header: [1, 2, 3, 4, 5, 6, false] }],
  ["bold", "italic", "underline", "strike"], // toggled buttons
  ["blockquote", "code-block"],
  [{ color: [] }, { background: [] }],
  [{ header: 1 }, { header: 2 }], // custom button values
  [{ list: "ordered" }, { list: "bullet" }],
  [{ direction: "rtl" }], // text direction
  ["image"],
  ["clean"], // remove formatting button
];

const form = useForm({
  title: props.blog ? props.blog.data.title : "",
  body: "",
  cover: null,
});

const body = ref({});

const handleReady = (quill) => {
  const html = props.blog ? props.blog.data.bodyHTML : "";
  const delta = quill.clipboard.convert(html);
  quill.setContents(delta);
};

const create = (html) => {
  form
    .transform((data) => ({
      ...data,
      body: html,
    }))
    .post(route("blogs.store"));
};

const update = (html) => {
  form
    .transform((data) => ({
      ...data,
      body: html,
      _method: "put",
    }))
    .post(route("blogs.edit", props.blog.data.id));
};

const submit = () => {
  let converter = new QuillDeltaToHtmlConverter(body.value.ops);
  let html = converter.convert();

  if (props.blog) update(html);
  else create(html);
};
</script>

<template>
  <div class="my-6">
    <form @submit.prevent="submit">
      <!-- Title -->
      <div>
        <label for="title">Title</label>
        <input id="title" type="text" v-model="form.title" />
        <InputError class="mt-2" :message="form.errors.title" />
      </div>
      <!-- /Title -->

      <!-- Body -->
      <div class="mt-4">
        <label for="body">Body</label>
        <div class="bg-white">
          <QuillEditor
            theme="snow"
            :toolbar="toolbar"
            :modules="modules"
            @ready="handleReady"
            v-model:content="body"
          />
        </div>
        <InputError class="mt-2" :message="form.errors.body" />
      </div>
      <!-- /Body -->

      <div class="mt-4">
        <div class="flex items-center">
          <label for="cover" class="mr-2">Cover: </label>
          <input
            type="file"
            name="cover"
            id="cover"
            @input="form.cover = $event.target.files[0]"
          />
        </div>
        <InputError class="mt-2" :message="form.errors.cover" />
      </div>

      <div class="mt-4 text-right">
        <PrimaryButton :disabled="form.processing">
          {{ blog ? "Update" : "Create" }}
        </PrimaryButton>
      </div>
    </form>
  </div>
</template>

// resources/js/Components/Blogs/CreateEditBlog.jsx
import React, { useMemo, useRef, useState } from "react";
import { useForm } from "@inertiajs/inertia-react";
import InputError from "@/Components/InputError.jsx";
import PrimaryButton from "@/Components/PrimaryButton.jsx";
import ImageUploader from "quill-image-uploader";
import axios from "axios";
import ReactQuill, { Quill } from "react-quill";
import "react-quill/dist/quill.snow.css";
import { Inertia } from "@inertiajs/inertia";

Quill.register("modules/imageUploader", ImageUploader);

export default function CreateEditBlog({ blog }) {
    const quillRef = useRef(null);

    const modules = useMemo(
        () => ({
            toolbar: {
                container: [
                    [{ header: [1, 2, 3, 4, 5, 6, false] }],
                    ["bold", "italic", "underline", "strike"], // toggled buttons
                    ["blockquote", "code-block"],
                    [{ color: [] }, { background: [] }],
                    [{ header: 1 }, { header: 2 }], // custom button values
                    [{ list: "ordered" }, { list: "bullet" }],
                    [{ direction: "rtl" }], // text direction
                    ["image"],
                    ["clean"], // remove formatting button
                ],
            },

            imageUploader: {
                upload: (file) => {
                    return new Promise((resolve, reject) => {
                        const formData = new FormData();
                        formData.append("image", file);

                        axios
                            .post("/upload-image", formData)
                            .then((res) => {
                                resolve(res.data.url);
                            })
                            .catch((err) => {
                                reject("Upload failed");
                            });
                    });
                },
            },
        }),
        []
    );

    const form = useForm({
        title: blog ? blog.data.title : "",
        body: blog ? blog.data.bodyHTML : "",
        cover: null,
        _method: blog ? "put" : "post",
    });

    const getDefaultValue = () => {
        const html = blog ? blog.data.bodyHTML : "";

        return html;
    };

    const create = (html) => {
        form.transform((data) => ({
            ...data,
            body: html,
        }));
        form.post(route("blogs.store"));
    };

    const update = (html) => {
        form.transform((data) => ({
            ...data,
            body: html,
        }));

        form.post(route("blogs.edit", blog.data.id));
    };

    const submit = (e) => {
        e.preventDefault();
        if (blog) update(quillRef.current.value);
        else create(quillRef.current.value);
    };

    return (
        <div className="my-6">
            <form onSubmit={submit}>
                <div>
                    <label htmlFor="title">Title</label>
                    <input
                        id="title"
                        type="text"
                        value={form.data.title}
                        onChange={(e) => form.setData("title", e.target.value)}
                    />
                    <InputError className="mt-2" message={form.errors.title} />
                </div>

                <div className="mt-4">
                    <label htmlFor="body">Body</label>
                    <div className="bg-white">
                        <ReactQuill
                            theme="snow"
                            modules={modules}
                            defaultValue={getDefaultValue()}
                            ref={quillRef}
                        />
                    </div>
                    <InputError className="mt-2" message={form.errors.body} />
                </div>

                <div className="mt-4">
                    <div className="flex items-center">
                        <label htmlFor="cover" className="mr-2">
                            Cover:{" "}
                        </label>
                        <input
                            type="file"
                            name="cover"
                            id="cover"
                            onChange={(e) =>
                                form.setData("cover", e.target.files[0])
                            }
                        />
                    </div>
                    <InputError className="mt-2" message={form.errors.cover} />
                </div>

                <div className="mt-4 text-right">
                    <PrimaryButton processing={form.processing}>
                        {blog ? "Update" : "Create"}
                    </PrimaryButton>
                </div>
            </form>
        </div>
    );
}
