// resources/js/Pages/Settings/Index.jsx
import React from "react";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.jsx";
import { Head } from "@inertiajs/inertia-react";
import General from "@/Components/Settings/General.jsx";
import Password from "@/Components/Settings/Password.jsx";

export default function Index(props) {
    return (
        <AuthenticatedLayout
            header={
                <h2 className="text-xl font-semibold leading-tight text-gray-800">
                    Settings
                </h2>
            }
        >
            <Head title="Settings" />

            <div className="grid grid-cols-1 gap-4 py-10 lg:grid-cols-2">
                <div>
                    <General />
                </div>
                <div>
                    <Password />
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/Settings/Index.vue
<script setup>
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import { Head } from "@inertiajs/inertia-vue3";
import General from "@/Components/Settings/General.vue";
import Password from "@/Components/Settings/Password.vue";
</script>

<template>
  <Head title="Settings" />

  <AuthenticatedLayout>
    <template #header>
      <h2 class="text-xl font-semibold leading-tight text-gray-800">
        Settings
      </h2>
    </template>

    <div class="grid grid-cols-1 gap-4 py-10 lg:grid-cols-2">
      <div>
        <General />
      </div>
      <div>
        <Password />
      </div>
    </div>
  </AuthenticatedLayout>
</template>
