// resources/js/Pages/Blogs/Create.vue
<script setup>
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import { Head } from "@inertiajs/inertia-vue3";
import CreateEditBlog from "@/Components/Blogs/CreateEditBlog.vue";
</script>

<template>
  <Head title="Create New Blog" />
  <AuthenticatedLayout>
    <CreateEditBlog />
  </AuthenticatedLayout>
</template>

// resources/js/Pages/Blogs/Create.jsx
import React from "react";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.jsx";
import { Head } from "@inertiajs/inertia-react";
import CreateEditBlog from "@/Components/Blogs/CreateEditBlog.jsx";

export default function Create() {
    return (
        <AuthenticatedLayout>
            <Head title="Create New Blog" />
            <CreateEditBlog />
        </AuthenticatedLayout>
    );
}
