// resources/js/Pages/Blogs/Edit.jsx
import React from "react";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.jsx";
import { Head } from "@inertiajs/inertia-react";
import CreateEditBlog from "@/Components/Blogs/CreateEditBlog.jsx";

export default function Edit({ blog }) {
    return (
        <AuthenticatedLayout>
            <Head title="Create New Blog" />
            <CreateEditBlog blog={blog} />
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/Blogs/Edit.vue
<script setup>
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import { Head } from "@inertiajs/inertia-vue3";
import CreateEditBlog from "@/Components/Blogs/CreateEditBlog.vue";

const props = defineProps(["blog"]);
</script>

<template>
  <Head title="Edit" />
  <AuthenticatedLayout>
    <CreateEditBlog :blog="blog" />
  </AuthenticatedLayout>
</template>
